FROM microsoft/dotnet:2.0-sdk AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY nuget.config ./
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -r win-x64 -o out

# build runtime image
FROM microsoft/nanoserver:10.0.14393.1715
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnetapp.exe"]
